// One page of semantic markup; every text node is populated from the dictionaries.
export function createLayout(i18n) {
  const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const text = key => `<span data-i18n="${key}">${escape(i18n.t(key))}</span>`;
  const aria = key => `data-i18n-aria-label="${key}" aria-label="${escape(i18n.t(key))}"`;
  const placeholder = key => `data-i18n-placeholder="${key}" placeholder="${escape(i18n.t(key))}"`;
  const eye = '<span class="eye-symbol" aria-hidden="true"><i></i></span>';
  const heading = section => `<span class="eyebrow">${text(`${section}.eyebrow`)}</span><h2>${text(`${section}.title`)}</h2>`;
  const counter = (value, decimals = 0) => `<span data-count="${value}" data-decimals="${decimals}">${i18n.format(0, decimals)}</span>`;
  const brand = `<span class="brand-mark" aria-hidden="true">𓂀</span><span>${text('nav.brand')}<small>${text('nav.sub')}</small></span>`;
  return `
  <a class="skip-link" href="#main">${text('a11y.skip')}</a>
  <div class="ambient" aria-hidden="true"><div class="orb orb-one"></div><div class="orb orb-two"></div><div id="particles"></div></div>
  <div class="topbar"><div class="wrap"><span>${text('hero.era')}</span><span><i class="live-dot"></i>${text('hero.status')}</span></div></div>
  <header class="header wrap"><a class="brand" href="#" data-quote-trigger="logo" ${aria('a11y.home')}>${brand}</a><nav ${aria('a11y.nav')}><a href="#mythology">${text('nav.mythology')}</a><a href="#chess">${text('nav.chess')}</a><a href="#faq">${text('nav.faq')}</a></nav><div class="header-controls"><div class="language-switch" role="group" ${aria('a11y.language')}><button type="button" data-language="sr" ${aria('a11y.sr')} aria-pressed="true">${text('languages.sr')}</button><span aria-hidden="true">|</span><button type="button" data-language="en" ${aria('a11y.en')} aria-pressed="false">${text('languages.en')}</button></div><button class="motion-toggle" type="button" id="motion-toggle" ${aria('a11y.pause')}><span aria-hidden="true">Ⅱ</span></button></div></header>
  <main id="main">
    <section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><span class="eyebrow hero-eyebrow"><span aria-hidden="true">𓆣</span>${text('hero.pretitle')}<span class="eyebrow-rule"></span></span><h1 id="hero-title">${text('hero.name')}<strong>${text('hero.title')}</strong></h1><p class="hero-subtitle">${text('hero.subtitle')}</p><p class="hero-description">${text('hero.description')} <em>${text('hero.valve')}</em></p><a href="#signup" class="button primary challenge-cta">${text('hero.cta')}<span aria-hidden="true">↗</span></a><p class="cta-support">${text('hero.support')}</p><div class="hero-badges">${i18n.t('hero.badges').map((_, i) => i === 2 ? `<a class="badge" href="#disclaimer" data-quote-trigger="badge"><span aria-hidden="true">◈</span>${text(`hero.badges.${i}`)}</a>` : `<button class="badge" type="button" data-quote-trigger="badge"><span aria-hidden="true">✧</span>${text(`hero.badges.${i}`)}</button>`).join('')}</div><p class="hero-warning">${text('hero.warning')}</p></div>
    <div class="pharaoh-panel"><div class="visual-top"><span><i class="live-dot"></i>${text('hero.visualTop')}</span><span>${text('hero.visualId')}</span></div><div class="pharaoh-scene"><div class="sun-disc" aria-hidden="true"></div><div class="orbit orbit-a" aria-hidden="true"></div><div class="orbit orbit-b" aria-hidden="true"></div><div class="hieroglyph-ring" aria-hidden="true">𓂀　𓆣　𓋹　𓊹　𓅃　𓂀　𓆣</div><div class="pyramid pyramid-left" aria-hidden="true"></div><div class="pyramid pyramid-right" aria-hidden="true"></div><div class="obelisk obelisk-left" aria-hidden="true"></div><div class="obelisk obelisk-right" aria-hidden="true"></div><button class="pharaoh-emblem" type="button" data-quote-trigger="decoration" ${aria('a11y.emblem')}><span class="pharaoh-collar" aria-hidden="true"></span><span class="nemes" aria-hidden="true"></span><span class="pharaoh-face" aria-hidden="true"><span class="pharaoh-brow"></span><span class="pharaoh-eyes"></span><span class="pharaoh-nose"></span><span class="pharaoh-beard"></span></span><span class="uraeus" aria-hidden="true">𓋹</span></button><div class="coordinates"><span>${text('hero.coord')}</span><span>${text('hero.power')}</span></div><div class="scan-line" aria-hidden="true"></div></div><div class="entity-label"><span class="micro">${text('hero.visualNote')}</span><strong>${text('hero.visualLabel')}</strong><span class="micro entity-glyphs" aria-hidden="true">𓂀 ─── 𓆣 ─── 𓂀</span></div><div class="visual-bottom"><span>${text('hero.node')}</span><span class="signal" aria-hidden="true">▂▄▆█</span></div></div></section>
    <div class="rotating-prophecy wrap"><span class="prophecy-mark" aria-hidden="true">𓋹</span><p id="rotating-subtitle"></p><span class="micro">${text('hero.uptime')}</span></div>
    <div class="ticker"><div class="ticker-track"><span data-i18n="ticker">${escape(i18n.t('ticker'))}</span><span data-i18n="ticker" aria-hidden="true">${escape(i18n.t('ticker'))}</span></div></div>
    <section class="stats wrap" ${aria('a11y.stats')}>${[99.97, 8492, 3, 14208].map((value, i) => `<div><span class="micro">${text(`stats.${i}.label`)}</span><strong class="${i === 2 ? 'danger' : ''}">${counter(value, i === 0 ? 2 : 0)}${i === 0 || i === 2 ? '<em>%</em>' : ''}</strong><small>${text(`stats.${i}.note`)}</small></div>`).join('')}</section>
    <section class="technology wrap section" id="core"><div class="section-intro">${heading('oracle')}<p>${text('oracle.description')}</p><div class="confidence"><i class="live-dot"></i><span>${text('oracle.confidence')}</span><b>${counter(100.000001, 6)}%</b></div><span class="micro muted">${text('oracle.review')}</span><div class="mini-pyramids" aria-hidden="true"><i></i><i></i><i></i><span>𓂀</span></div></div><div class="telemetry panel"><div class="panel-heading"><div><strong>${text('oracle.name')}</strong><span class="micro">${text('oracle.subtitle')}</span></div>${eye}</div><div class="telemetry-body"><div class="oracle-status"><i class="live-dot"></i>${text('oracle.status')}</div><div class="telemetry-grid">${i18n.t('oracle.telemetry').map((_, i) => `<div class="telemetry-row"><span>${text(`oracle.telemetry.${i}.label`)}</span><b class="${i === 5 ? 'danger' : ''}"><i class="status-dot"></i>${text(`oracle.telemetry.${i}.value`)}</b></div>`).join('')}</div><div class="chart" aria-hidden="true"></div><div class="micro muted chart-caption">${text('oracle.chart')}</div><div class="gpu-line"><span class="micro">${text('oracle.gpu')}</span><span id="gpu-load" class="micro"></span></div><button class="text-button" type="button" data-quote-trigger="oracle">${text('oracle.action')} <span aria-hidden="true">↗</span></button></div><div class="scan-line" aria-hidden="true"></div></div></section>
    <section class="mythology section wrap" id="mythology"><div class="section-heading"><div>${heading('mythology')}</div><p>${text('mythology.description')}</p></div><div class="tablet-grid">${i18n.t('mythology.facts').map((fact, i) => `<article class="tablet" data-lore-id="${fact.id}"><div class="tablet-top"><span aria-hidden="true">${['𓆣', '𓅃', '𓋹', '𓇳', '𓂀', '𓊹'][i % 6]}</span><span class="micro">${text('mythology.tablet')} / ${String(i + 1).padStart(3, '0')}</span></div><h3>${text(`mythology.facts.${i}.title`)}</h3><p>${text(`mythology.facts.${i}.text`)}</p><button class="text-button" type="button" data-quote-trigger="myth">${text('mythology.action')} <span aria-hidden="true">↗</span></button></article>`).join('')}</div></section>
    <aside class="archaeology wrap"><div class="stone-inscription"><span class="stone-glyphs" aria-hidden="true">𓅓 𓇋 𓂧 𓂀 𓆣</span><strong>${text('archaeology.inscription')}</strong><span class="micro">${text('archaeology.coordinate')}</span></div><div><span class="eyebrow">${text('archaeology.label')}</span><h3>${text('archaeology.title')}</h3><p>${text('archaeology.text')}</p><p class="gold">${text('archaeology.age')}</p><small>${text('archaeology.note')}</small></div><div class="archaeology-seal" aria-hidden="true">${text('archaeology.seal')}</div></aside>
    <section class="chess section wrap" id="chess"><div class="chess-copy">${heading('chess')}<p class="chess-subtitle">${text('chess.subtitle')}</p><p>${text('chess.text')}</p><p>${text('chess.detail')}</p><blockquote>${text('chess.doctrine')}</blockquote><span class="micro gold">${text('chess.grandmaster')}</span></div><div class="chess-panel panel"><div class="panel-heading"><strong>${text('chess.name')}</strong><span aria-hidden="true">∞</span></div><div class="chess-stage" aria-hidden="true"><div class="chess-board">${Array.from({ length: 64 }, (_, i) => `<i class="${(Math.floor(i / 8) + i % 8) % 2 ? 'dark-square' : ''}"></i>`).join('')}</div><span class="chess-piece king">♚</span><span class="chess-piece pawn">♟</span><span class="chess-piece fallen">♜</span><span class="chess-orbit"></span></div><div class="chess-caption micro">${text('chess.move')}</div><div class="chess-data"><div><span>${text('chess.depth')}</span><b>∞</b></div><div><span>${text('chess.variations')}</span><b data-number="14882943112"></b></div><div><span>${text('chess.opponent')}</span><b>${text('chess.known')}</b></div><div><span>${text('chess.rade')}</span><b class="purple">${text('chess.classified')}</b></div></div><button class="text-button" type="button" data-quote-trigger="chess">${text('chess.action')} <span aria-hidden="true">↗</span></button></div></section>
    <section class="why section wrap" id="why"><div class="section-heading"><div>${heading('why')}</div><span class="micro muted">${text('why.note')}</span></div><div class="why-grid">${i18n.t('why.cards').map((_, i) => `<article class="why-card"><div class="card-top"><span aria-hidden="true">${['⌖', '𓂀', '♜'][i]}</span><span class="micro">0${i + 1}</span></div><h3>${text(`why.cards.${i}.title`)}</h3><p>${text(`why.cards.${i}.text`)}</p><span class="micro gold">${text(`why.cards.${i}.label`)}</span></article>`).join('')}</div></section>
    <section class="science wrap"><span class="micro">${text('science.label')}</span><blockquote>${text('science.text')}</blockquote><span class="micro muted">${text('science.author')}</span></section>
    <section class="signup section wrap" id="signup"><div class="signup-copy">${heading('signup')}<p>${text('signup.subtitle')}</p><div class="warning"><span aria-hidden="true">⚠</span><div><strong>${text('signup.warning')}</strong><p>${text('signup.warningText')}</p></div></div><div class="signup-facts">${i18n.t('signup.facts').map((_, i) => `<span><span aria-hidden="true">✓ </span>${text(`signup.facts.${i}`)}</span>`).join('')}</div><small class="muted">${text('signup.exit')}</small><div class="signup-ornament" aria-hidden="true">𓅃 ─── 𓂀 ─── 𓅃</div></div><div class="form-panel panel"><div class="panel-heading"><span>${text('signup.panel')}</span><span class="online"><i class="live-dot"></i>${text('signup.status')}</span></div>
    <form id="signup-form" novalidate><div class="field"><label for="steamNick">${text('signup.nick')}<small>${text('signup.required')}</small></label><input id="steamNick" name="steamNick" ${placeholder('signup.nickPlaceholder')} maxlength="64" required autocomplete="nickname" aria-describedby="form-error"></div><div class="field"><label for="steamLink">${text('signup.link')}<small>${text('signup.required')}</small></label><input id="steamLink" name="steamLink" type="url" ${placeholder('signup.linkPlaceholder')} maxlength="256" required inputmode="url" aria-describedby="steam-help form-error"><small id="steam-help">${text('signup.linkHelp')}</small></div><div class="field"><label for="mmr">${text('signup.mmr')}<small>${text('signup.honest')}</small></label><input id="mmr" name="mmr" type="number" min="0" max="20000" step="1" ${placeholder('signup.mmrPlaceholder')} required inputmode="numeric" aria-describedby="form-error"></div><div class="honeypot" aria-hidden="true"><label for="website">${text('signup.honeypot')}</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div><p class="analysis-line"><i class="live-dot"></i>${text('signup.analysis')}</p><p id="form-error" class="error" role="alert" hidden></p><button class="button primary submit" type="submit">${text('signup.submit')}<span aria-hidden="true">↗</span></button><p class="form-note">${text('signup.private')}<br><a href="#privacy">${text('signup.privacy')}</a></p></form>
    <div id="processing" class="result" hidden tabindex="-1"><div class="processing-orb" aria-hidden="true">𓆣</div><span class="micro gold">${text('signup.processingLabel')}</span><h3 id="processing-text" role="status"></h3><div class="processing-track" aria-hidden="true"><i></i></div><p>${text('signup.processingNote')}</p></div><div id="success" class="result" hidden tabindex="-1">${eye}<span class="micro online">${text('signup.acceptedLabel')}</span><h3>${text('signup.accepted')}</h3><p>${text('signup.acceptedText')}</p><div class="verdict-stamp">${text('signup.stamp')}</div><small class="muted stamp-note">${text('signup.stampNote')}</small><div class="survival"><span>${text('signup.survival')}</span><strong id="survival"></strong><small>${text('signup.survivalNote')}</small></div><p class="luck">${text('signup.luck')}</p><button id="return-button" class="button secondary" type="button">${text('signup.return')}<span aria-hidden="true">↗</span></button></div></div></section>
    <section class="faq section wrap" id="faq"><div class="section-heading"><div>${heading('faq')}</div><p>${text('faq.description')}</p></div><div class="faq-list">${i18n.t('faq.entries').map((entry, i) => `<details data-faq-id="${entry.id}"><summary><span class="faq-number" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span><span>${text(`faq.entries.${i}.question`)}</span><span class="faq-plus" aria-hidden="true">+</span></summary><div class="faq-answer"><span class="faq-glyph" aria-hidden="true">𓂀</span><p>${text(`faq.entries.${i}.answer`)}</p></div></details>`).join('')}</div></section>
  </main>
  <footer class="wrap"><div class="footer-top"><a class="brand" href="#" data-quote-trigger="logo"><span class="brand-mark" aria-hidden="true">𓂀</span><span>${text('footer.name')}<small>${text('footer.brand')}</small></span></a><p>${text('footer.powered')}</p><span class="footer-status"><i class="live-dot"></i>${text('footer.status')}</span></div><div class="footer-links"><a href="#terms">${text('footer.terms')}</a><a href="#signup" class="challenge-cta">${text('footer.protocol')}</a><a href="#privacy">${text('footer.privacy')}</a><a href="#contact">${text('footer.contact')}</a></div><div class="legal-details">${['terms', 'privacy', 'contact'].map(key => `<details id="${key}"><summary>${text(`footer.${key}`)}</summary><p>${text(`footer.${key}Text`)}</p></details>`).join('')}</div><div class="disclaimers" id="disclaimer"><p>${text('footer.verification')}</p><p>${text('footer.joke')}</p><p>${text('footer.valve')}</p><span>${text('footer.copyright')}</span></div></footer>
  <aside id="quote-toast" class="quote-toast" hidden><button id="quote-close" type="button" ${aria('a11y.quoteClose')}><span aria-hidden="true">×</span></button><div class="quote-heading"><span aria-hidden="true">𓂀</span><span id="quote-label"></span></div><div id="quote-announcement" role="status" aria-live="polite" aria-atomic="true"><p id="quote-text"></p></div><span class="micro muted">${text('quote.source')}</span><div class="quote-timer" aria-hidden="true"></div></aside>
  <div id="judgment" class="judgment" hidden aria-hidden="true"><div class="judgment-halo">${eye}<div class="judgment-glyphs">𓂀　𓆣　𓋹　𓅃　𓂀</div><span class="micro">${text('signup.judgmentLabel')}</span><strong>${text('signup.stamp')}</strong></div></div>`;
}
